language: c

compiler: 
  - gcc
  - clang

os:
  - linux

python:
  - "3.6"

install:
  - pip3 install --user sphinx
  - pip3 install --user -r docs/requirements.txt

script: ./test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
