language: c

dist: bionic

compiler: 
  - gcc
  - clang

os:
  - linux

install:
  - sudo apt-get update
  - sudo apt-get install valgrind
  - sudo apt-get install python3
  - pip3 install --user sphinx
  - pip3 install --user -r docs/requirements.txt

script: ./test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
