language: c

compiler: 
  - gcc
  - clang

os:
  - linux

install:
  - pip3 install sphinx
  - pip3 install -r docs/requirements.txt

script: ./test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
