language: c

compiler: 
  - gcc
  - clang

os:
  - linux

install:
  - pip install --user sphinx
  - pip install --user -r docs/requirements.txt

script: ./test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
